# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GitSlot < Formula
  desc "Manage git worktrees as fixed, named slots"
  homepage "https://github.com/AquiTCD/git-slot"
  version "0.9.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/AquiTCD/git-slot/releases/download/v0.9.0/git-slot_0.9.0_darwin_amd64.tar.gz"
      sha256 "f28a8f768de700d576ad9eec1c7025368886f7a07edf097c57da6d1780b84bf3"

      define_method(:install) do
        bin.install "git-slot"
        generate_completions_from_executable(bin/"git-slot", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/AquiTCD/git-slot/releases/download/v0.9.0/git-slot_0.9.0_darwin_arm64.tar.gz"
      sha256 "84ebd1b6b6670fb2731f215a791449d182db51db8225f6e423492725195dc1a0"

      define_method(:install) do
        bin.install "git-slot"
        generate_completions_from_executable(bin/"git-slot", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/AquiTCD/git-slot/releases/download/v0.9.0/git-slot_0.9.0_linux_amd64.tar.gz"
      sha256 "61c782a890292d416f73535e8f10f38d72ce257ad5dd1486c84fd62c8788cf81"
      define_method(:install) do
        bin.install "git-slot"
        generate_completions_from_executable(bin/"git-slot", "completion")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/AquiTCD/git-slot/releases/download/v0.9.0/git-slot_0.9.0_linux_arm64.tar.gz"
      sha256 "9ec4888ac7ccc7e7b51ad187565985e738296f20a1309834ab7b816be446ed2c"
      define_method(:install) do
        bin.install "git-slot"
        generate_completions_from_executable(bin/"git-slot", "completion")
      end
    end
  end

  test do
    system "#{bin}/git-slot", "--version"
  end
end
