# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GitSlot < Formula
  desc "Manage git worktrees as fixed, named slots"
  homepage "https://github.com/AquiTCD/git-slot"
  version "0.5.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/AquiTCD/git-slot/releases/download/v0.5.1/git-slot_0.5.1_darwin_amd64.tar.gz"
      sha256 "f651855708cbbd067455a4a0e134a0293c9e8731ba5f1a0854b21d0ac7b508b6"

      define_method(:install) do
        bin.install "git-slot"
        generate_completions_from_executable(bin/"git-slot", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/AquiTCD/git-slot/releases/download/v0.5.1/git-slot_0.5.1_darwin_arm64.tar.gz"
      sha256 "9bb1c19cd687df557553a1628e9d3122b37d199dc4df5aaaf2eaeb981ddd7c9e"

      define_method(:install) do
        bin.install "git-slot"
        generate_completions_from_executable(bin/"git-slot", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/AquiTCD/git-slot/releases/download/v0.5.1/git-slot_0.5.1_linux_amd64.tar.gz"
      sha256 "c439a2e907544b05004a43cc5c2dde9a6249739ceeada9c7bc7631a5b3d183bf"
      define_method(:install) do
        bin.install "git-slot"
        generate_completions_from_executable(bin/"git-slot", "completion")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/AquiTCD/git-slot/releases/download/v0.5.1/git-slot_0.5.1_linux_arm64.tar.gz"
      sha256 "9bfca6f837c030d2ed0adfccfe3b7fec8491695f59517128761072b8cbca5910"
      define_method(:install) do
        bin.install "git-slot"
        generate_completions_from_executable(bin/"git-slot", "completion")
      end
    end
  end

  test do
    system "#{bin}/git-slot", "--version"
  end
end
