# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GitSlot < Formula
  desc "Manage git worktrees as fixed, named slots"
  homepage "https://github.com/AquiTCD/git-slot"
  version "0.8.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/AquiTCD/git-slot/releases/download/v0.8.1/git-slot_0.8.1_darwin_amd64.tar.gz"
      sha256 "a71a6a62f0b32e58c79519198cb0cd8c337f77d60fbd395048cfb8acb36f3caa"

      define_method(:install) do
        bin.install "git-slot"
        generate_completions_from_executable(bin/"git-slot", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/AquiTCD/git-slot/releases/download/v0.8.1/git-slot_0.8.1_darwin_arm64.tar.gz"
      sha256 "82e23afc011bb56cc0b0f7657e2348825c17844f8aaec2bf53a61f7586f8c33d"

      define_method(:install) do
        bin.install "git-slot"
        generate_completions_from_executable(bin/"git-slot", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/AquiTCD/git-slot/releases/download/v0.8.1/git-slot_0.8.1_linux_amd64.tar.gz"
      sha256 "c19b5be56d8d7f63c025139dfcb2303afae89a5397949d7a473b3b044f32f2ce"
      define_method(:install) do
        bin.install "git-slot"
        generate_completions_from_executable(bin/"git-slot", "completion")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/AquiTCD/git-slot/releases/download/v0.8.1/git-slot_0.8.1_linux_arm64.tar.gz"
      sha256 "a35adcc1ae7bbad342f244a2bd1d56d623fea81c87c20c7da868e10acfd3fd41"
      define_method(:install) do
        bin.install "git-slot"
        generate_completions_from_executable(bin/"git-slot", "completion")
      end
    end
  end

  test do
    system "#{bin}/git-slot", "--version"
  end
end
